name: CI Pipeline for FlaskApp

on: 
  push: 
    branches:
      - main  # ou une autre branche si vous le souhaitez
  pull_request: 
    branches:
      - main  # ou une autre branche si vous le souhaitez

jobs: 
  build: 
    runs-on: ubuntu-latest  # Utilisation de l'OS Ubuntu pour le runner GitHub Actions

    steps:
    # Étape 1: Récupérer le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v3  # Vérifie le code du dépôt

    # Étape 2: Se connecter à Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Action pour se connecter à Docker Hub
      with:
        username: ${{ secrets.Ndeye}}  # Utilisation du secret Docker Username
        password: ${{ secrets.MINTOu77*}}  # Utilisation du secret Docker Password

    # Étape 3: Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Utilisez une version stable de Python

    # Étape 4: Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Mettre à jour pip
        pip install -r requirements.txt  # Installer les dépendances à partir du fichier requirements.txt

    # Étape 5: Exécuter les tests
    - name: Run tests
      run: |
        pytest  # Ou toute autre commande pour exécuter vos tests
