name: CI Pipeline for FlaskApp

on:
  push:
    branches:
      - main  # Le pipeline s'exécute sur chaque push vers la branche master
  pull_request:
    branches:
      - main  # Le pipeline s'exécute sur chaque PR vers la branche master

jobs:
  build:
    runs-on: ubuntu-latest  # L'environnement de runner (Ubuntu pour ce cas)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout du code pour récupérer les fichiers

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Vous pouvez ajuster cette version selon votre projet

    - name: Set up virtual environment
      run: |
        python -m venv venv  # Création d'un environnement virtuel
        source venv/bin/activate  # Activation de l'environnement virtuel

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Mettre à jour pip
        pip install -r requirements.txt  # Installer les dépendances à partir de requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate  # Réactiver l'environnement virtuel
        pytest  # Exécution des tests avec pytest
